name: transito
description: A bus timing application to view your bus arrival timings in Singapore swiftly.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+21

environment:
  sdk: '>=3.1.0 <4.0.0'

scripts:
  dev: firebase emulators:start; flutter run

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  jiffy: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  provider: ^6.0.3
  json_annotation: ^4.8.1
  http: ^1.1.0
  alphanum_comparator: ^2.0.1
  photo_view: ^0.14.0
  flutter_svg: ^2.0.7
  parent_child_checkbox:
    git:
      url: https://github.com/TechSupportz/parent-child-checkbox
  is_first_run: ^1.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  android_intent_plus: ^4.0.2
  url_launcher: ^6.1.5
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0
  flutter_map: ^5.0.0
  form_builder_extra_fields: ^10.0.0
  flutter_native_splash: ^2.1.2+1
  skeletons: ^0.0.3
  package_info_plus: ^4.1.0
  upgrader: ^8.1.0
  shared_preferences: ^2.2.2
  posthog_flutter: ^3.3.0
  measure_size: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.1.11


flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  image: "assets/images/logo.png"
  android_12:
    image: "assets/icons/a12-splash-1152x1152.png"
    icon_background_color: "#030108"
    color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - shorebird.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf


